#!/bin/bash -ex

if [[ -z $CI ]]; then
  YAPF_ARG="-i"
  STANDARD_ARG="--fix"
else
  YAPF_ARG="-d"
  STANDARD_ARG=""
fi

# format Python
yapf -r -vv $YAPF_ARG minerva tests examples

# format JavaScript
npx standard $STANDARD_ARG front 'front/**/*.js' 'front/*.js' '*.js'
