#!/bin/bash -eux

if [ $# = 0 ]; then
  YAPF_ARG="-i"
  STANDARD_ARG="--fix"
else
  YAPF_ARG=$*
  STANDARD_ARG=""
fi

# format Python
yapf -r -vv $YAPF_ARG minerva tests examples

# format JavaScript
npx standard $STANDARD_ARG front 'front/**/*.js' 'front/*.js' '*.js'

# check SCSS format
npx sass-lint 'front/styles/*.scss' -v -q

# ESLint check
npm run lint
