#!/bin/bash -eux

# create temporary directory for tests
rm -rf test_data
mkdir -p test_data

# run tests
echo "Run unit tests"
pytest --cov-report=xml --cov=minerva tests -p no:warnings -v

# clean up
rm -r test_data

# build javascript
npm run build
